### ISSUE TITLE
trial accounts: creation very slow

### ISSUE THREAD

**Issue by juliand665** [mangelio/web#120]
The `/trial/create_account` endpoint takes a good 30 seconds to process appropriate requests, which seems like rather a lot.

**Comment by juliand665** [comment]
While we're at it, could we perhaps shorten trial usernames a little? Now that #119 is planned, we could do that pretty well. I suggest removing the `.dev.app` so it's just `@test.mangel.io`; that'd help make this screen look a little less ridiculous:

![image](https://user-images.githubusercontent.com/827762/52527405-63be2d80-2cc8-11e9-9fb4-dd07d49cd51e.png)

**Comment by famoser** [comment]
the trial usernames are already shorter. the performance issue is still unresolved

**Comment by famoser** [comment]
I can not reproduce this locally. It could be that this is an issue with the server, as it performs badly when creating a lot of files.

**Comment by famoser** [comment]
#152 will also have an impact on this

**Comment by famoser** [comment]
will close because no way to reproduce, but will retest as soon as new trial construction site exists
