### ISSUE TITLE
align wording

### ISSUE THREAD

**Issue by famoser** [mangelio/web#247]
align wording with the app & shorten strings wherever possible

**Comment by famoser** [comment]
concrete:
- [ ] map (Karte, Plan) -> construction plan (Bauplan)
- [ ] craftsman (firma, handwerker, ausführendes unternehmen) -> contractor (unternehmer)
- [ ] answered (beantwortet) -> completed (erledigt) as the third status of an issue

**Comment by famoser** [comment]
After the concrete points are resolved, keep as an enhancement to align possibly missed wordings with the app

**Comment by juliand665** [comment]
Would this rename also concern variable/function/type names in code?

**Comment by famoser** [comment]
No because I guess this will change again in the future
