### ISSUE TITLE
api: changing map's parent doesn't mark parent as changed

### ISSUE THREAD

**Issue by juliand665** [mangelio/web#262]
With the current api, maps specify their children rather than their parent, so when a parent-child relationship changes, it's expected that this is reflected in the parent's `lastChangeTime` updating, rather than the child's. However, the opposite is currently the case. This results in the client not obtaining the information it needs from a sync.

**Comment by juliand665** [comment]
This would require a really ugly and badly-performing workaround; it would be great if the API could either still ship the child map (in addition to the parent map), allowing me to restrict myself to modifying just the `changedMaps` i get.

**Comment by famoser** [comment]
The change of parent is technically a change in the child, as the child's parentId is updated. Its unfortunate that the current API design leads to this bad behaviour. This should be resolved with #158.

Until then I will add a fix.
